### PR TITLE
Adding `description` to `setup.py`

### PR DESCRIPTION
**Pull request by lowks**
Adding `description` to `setup.py`. This will be picked up automatically when uploading to `pypi` so that project will not be listed as `UNKNOWN`

### CODE REVIEW

**Comment by stefan-koch-micro** [comment]
Great idea.  Thank you for noticing and pointing it out.   

I do not like you description of 'Python module to do reporting calculations'.  It is too generic for what I am trying to accomplish.   (This is understandable of course.)  I would prefer 'Python package for gas adsorption calculations and support tools.')

I am really new to publishing code like this.  So, I am not sure which is more polite: to let you change it so you get credit for the commit, or to change it myself because you have helped enough already.   

Thanks again.

**Comment by lowks** [comment]
I just followed what was in your README, let me update the PR (Pull Request)

**Comment by lowks** [comment]
Done :+1:

**Comment by stefan-koch-micro** [comment]
Thanks.

**Pull request merged**
